// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJteuEMOwEztLyTbzvACdLnd91SYgsiBY',
    appId: '1:848402154158:web:32f2cfda3c0b05ab0fa33f',
    messagingSenderId: '848402154158',
    projectId: 'nursing-exam-app-a7184',
    authDomain: 'nursing-exam-app-a7184.firebaseapp.com',
    storageBucket: 'nursing-exam-app-a7184.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5-tfphpOzM5GKWioDea1xyGIeFiciJ5k',
    appId: '1:848402154158:android:5448b9a80b697a440fa33f',
    messagingSenderId: '848402154158',
    projectId: 'nursing-exam-app-a7184',
    storageBucket: 'nursing-exam-app-a7184.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMfvOCoU03e7XabWg5x70GuIuwV5vCkG4',
    appId: '1:848402154158:ios:d3aa658067003f280fa33f',
    messagingSenderId: '848402154158',
    projectId: 'nursing-exam-app-a7184',
    storageBucket: 'nursing-exam-app-a7184.firebasestorage.app',
    iosBundleId: 'com.example.nursingExamApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMfvOCoU03e7XabWg5x70GuIuwV5vCkG4',
    appId: '1:848402154158:ios:d3aa658067003f280fa33f',
    messagingSenderId: '848402154158',
    projectId: 'nursing-exam-app-a7184',
    storageBucket: 'nursing-exam-app-a7184.firebasestorage.app',
    iosBundleId: 'com.example.nursingExamApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJteuEMOwEztLyTbzvACdLnd91SYgsiBY',
    appId: '1:848402154158:web:8f8d7005a3cb1f3b0fa33f',
    messagingSenderId: '848402154158',
    projectId: 'nursing-exam-app-a7184',
    authDomain: 'nursing-exam-app-a7184.firebaseapp.com',
    storageBucket: 'nursing-exam-app-a7184.firebasestorage.app',
  );
}
